#!/bin/bash

# Run multi-gadget setup script.
sudo /home/pi/uvc-gadget/multi-gadget.sh

# Set some camera control options.
/usr/bin/v4l2-ctl -c auto_exposure=0
/usr/bin/v4l2-ctl -c auto_exposure_bias=8
/usr/bin/v4l2-ctl -c contrast=20
/usr/bin/v4l2-ctl -c video_bitrate=25000000

# Configure the stream with uvc-gadget.
sudo /home/pi/uvc-gadget/uvc-gadget -f1 -s1 -r0 -u /dev/video1 -v /dev/video0
